networks:
  app_network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: postgres-open-care
    networks:
      - app_network
    environment:
      POSTGRES_DB: open-care
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Code#Prophet2024
    ports:
      - "5434:5432" # Changed host port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: open-care-backend
    networks:
      - app_network
    ports:
      - "6500:6500"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-open-care:5432/open-care?currentSchema=public
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Code#Prophet2024
    depends_on:
      - postgres

volumes:
  postgres_data:
