services:
     postgres:
          image: postgres:16
          volumes:
               - postgres_data:/var/lib/postgresql/data
          ports:
               - "5444:5432"
          environment:
               POSTGRES_DB: keycloak
               POSTGRES_USER: keycloak
               POSTGRES_PASSWORD: password
          healthcheck:
               test: ["CMD-SHELL", "pg_isready -U keycloak"]
               interval: 10s
               timeout: 5s
               retries: 5

     keycloak:
          image: quay.io/keycloak/keycloak:latest
          volumes:
               - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
          command:
               - start-dev
               - --import-realm
          environment:
               KC_DB: postgres
               KC_DB_URL_HOST: postgres
               KC_DB_URL_DATABASE: keycloak
               KC_DB_USERNAME: keycloak
               KC_DB_PASSWORD: password
               KEYCLOAK_ADMIN: admin
               KEYCLOAK_ADMIN_PASSWORD: admin
          ports:
               - "8080:8080"
          depends_on:
               postgres:
                    condition: service_healthy

volumes:
     postgres_data: