version: '3.9'

services:
     db:
          image: mariadb:11
          restart: always
          command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
          volumes:
               - db:/var/lib/mysql
          environment:
               MYSQL_ROOT_PASSWORD: mysecretroot
               MYSQL_PASSWORD: mysecret
               MYSQL_DATABASE: nextcloud
               MYSQL_USER: nextcloud

     app:
          image: nextcloud:latest
          restart: always
          ports:
               - 8081:80
          links:
               - db
          volumes:
               - nextcloud:/var/www/html
          environment:
               MYSQL_PASSWORD: mysecret
               MYSQL_DATABASE: nextcloud
               MYSQL_USER: nextcloud
               MYSQL_HOST: db

volumes:
     db:
     nextcloud:
