server:
  port: 6500

spring:
  application:
    name: open-care-backend

  # Postgres configuration
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/open_care_new
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:12345678}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    drop-first: false
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # Keycloak Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/opencare
          jwk-set-uri: http://localhost:8080/realms/opencare/protocol/openid-connect/certs

  # Connection timeouts
  mvc:
    async:
      request-timeout: 30000

# Keycloak connections
app:
  keycloak:
    server-url: http://localhost:8080
    realm: opencare
    client-id: open-care-backend
    client-secret: u3L5IEUSLoBoPzFghcMUvdSJSUedr6Fm
    admin:
      client-id: admin-cli
      username: admin
      password: admin

  # Rate limiting
  rate-limiting:
    enabled: true
    limit: 100
    refresh-period: 60

  # Application URLs
  frontend:
    redirect-uri: http://localhost:5173

# Security headers
security:
  headers:
    content-security-policy: "default-src 'self'; frame-ancestors 'none'"
    strict-transport-security: "max-age=31536000; includeSubDomains"

# Swagger Configuration
springdoc:
  show-actuator: false
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    tags-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: 0
    filter: true
    enabled: true
  api-docs:
    path: /api-docs/public
    enabled: true
  disable-i18n: true

# Logging Configuration
logging:
  level:
    root: error
    sql: debug
    web: debug