server:
  port: ${SERVER_PORT:6700}

spring:
  application:
    name: open-care-backend

  # Postgres configuration
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/open_care
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:12345678}

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    drop-first: false
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # Keycloak Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:opencare}
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:opencare}/protocol/openid-connect/certs

  # Connection timeouts
  mvc:
    async:
      request-timeout: 30000

  # cache configuration
  cache:
    type: caffeine
    cache-names:
      - githubContributors
      - latestBlogPosts
      - topDoctors
    caffeine:
      spec: maximumSize=100,expireAfterWrite=30m

# Keycloak connections
app:
  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    realm: ${KEYCLOAK_REALM:opencare}
    client-id: ${KEYCLOAK_CLIENT_ID:open-care-backend}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:u3L5IEUSLoBoPzFghcMUvdSJSUedr6Fm}
    admin:
      realm: ${KEYCLOAK_ADMIN_REALM:master}
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
      username: ${KEYCLOAK_ADMIN_USERNAME:admin}
      password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

  # Rate limiting
  rate-limiting:
    enabled: ${RATE_LIMITING_ENABLED:true}
    limit: ${RATE_LIMITING_LIMIT:100}
    refresh-period: ${RATE_LIMITING_REFRESH_PERIOD:60}

  # Application URLs
  frontend:
    redirect-uri: ${FRONTEND_REDIRECT_URI:http://localhost:5173}

# Security headers
security:
  headers:
    content-security-policy: "default-src 'self'; frame-ancestors 'none'"
    strict-transport-security: "max-age=31536000; includeSubDomains"

# Swagger Configuration
springdoc:
  show-actuator: false
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    tags-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: 0
    filter: true
    enabled: true
  api-docs:
    path: /api-docs/public
    enabled: true
  disable-i18n: true

# Logging Configuration
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:error}
    sql: ${LOGGING_LEVEL_SQL:debug}
    web: ${LOGGING_LEVEL_WEB:debug}

# Minio Configuration
minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin123}
  bucketName: ${MINIO_BUCKET_NAME:opencare}

# GitHub Configuration
github:
  token: ${GITHUB_TOKEN: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}
  repositories:
    - Cipher-Text/open-care-frontend
    - Cipher-Text/opencare