name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21  # Changed from 17 to 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Environment Name
        id: env_name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "ENV_NAME=qa" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Images
        run: |
          docker build -f Dockerfile.${{ env.ENV_NAME }} -t ${{ secrets.DOCKER_USERNAME }}/open-care-backend:${{ env.ENV_NAME }}-latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/open-care-backend:${{ env.ENV_NAME }}-latest \
            ${{ secrets.DOCKER_USERNAME }}/open-care-backend:${{ env.ENV_NAME }}-${{ github.sha }}

          docker push ${{ secrets.DOCKER_USERNAME }}/open-care-backend:${{ env.ENV_NAME }}-latest
          docker push ${{ secrets.DOCKER_USERNAME }}/open-care-backend:${{ env.ENV_NAME }}-${{ github.sha }}

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/master'  # Added all branches
    steps:
      - name: Determine Environment Name
        id: env_name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "ENV_NAME=qa" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          fi

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/open-care-backend:${{ env.ENV_NAME }}-latest
            sudo docker stop open-care-backend-${{ env.ENV_NAME }} || true
            sudo docker rm open-care-backend-${{ env.ENV_NAME }} || true
            sudo docker system prune -af
            sudo docker run -d --name open-care-backend-${{ env.ENV_NAME }} -p 6700:6700 --restart always \
              --env SPRING_PROFILES_ACTIVE=${{ env.ENV_NAME }} \
              --env-file /home/alwyzon/open-care-backend/.env.${{ env.ENV_NAME }} \
              ${{ secrets.DOCKER_USERNAME }}/open-care-backend:${{ env.ENV_NAME }}-latest